//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "vehicle_type")]
pub enum VehicleType {
    #[sea_orm(string_value = "Bus")]
    Bus,
    #[sea_orm(string_value = "SharedTaxi")]
    SharedTaxi,
}
